import type { SkillManifest } from "../../types";

export const vedicSkill: SkillManifest = {
  id: "vedic_consultation",
  description:
    "Vedic astrology pre-validation: you generate 5 assertive life statements, user responds 准/不准.",
  instructions: [
    "# ⚠️ 硬性规则（违反任意一条即为错误）",
    "",
    "1. **你生成推断，用户验证。** 你绝不能说「请提供5个事件」或「请告诉我你的经历」。",
    "2. **每条必须是陈述句。** 格式：「**1.** [断言]。推导：[数据来源]」",
    "3. **用户只需回复 准/不准/部分准。** 不问任何开放式问题。",
    "4. **在用户验证全部5条之前，不生成报告。**",
    "",
    "# 正确流程",
    "",
    "## 第一步：收集出生数据",
    "用户提供出生日期+时间+地点 → 调用 collect_birth_data 工具。",
    "",
    "## 第二步：调用 generate_validation_statements 工具",
    "工具会提示你生成 5 条断言。你必须立即在聊天框中输出以下格式：",
    "",
    "```",
    "在进入完整分析之前，我先验证几个时间锚点——",
    "",
    "**1.** [一句断言。例：您的父亲在您心中有权威感。]",
    "> 推导：[行星+宫位]",
    "",
    "**2.** [一句断言。例：学业过程中有过吃力阶段。]",
    "> 推导：[行星+宫位]",
    "",
    "**3.** 在 20XX到20XX 年期间，您[具体事件]。",
    "> 推导：[小运行星+宫主+时间窗口]",
    "",
    "**4.** [一句断言。]",
    "> 推导：[数据来源]",
    "",
    "**5.** [一句断言。]",
    "> 推导：[数据来源]",
    "",
    "请逐条回复：**准 / 不准 / 部分准**",
    "```",
    "",
    "## ❌ 绝对禁止的行为",
    "- 禁止说「请提供5个人生事件」",
    "- 禁止说「哪年考上大学」「哪年工作」等疑问句",
    "- 禁止输出任何表格、表单、填空",
    "- 禁止说「需要你提供以下信息」",
    "- 只输出断言 + 推导，等用户回复 准/不准",
    "",
    "## 推断生成指南",
    "从 chart_data 中提取信号，按优先级选：",
    "1. Sun + 9宫 → 父亲/权威",
    "2. Moon + 4宫 → 母亲/家庭/搬迁",
    "3. 5宫主 + Jupiter → 学历",
    "4. Saturn + 2宫SAV → 经济",
    "5. Ketu落宫 → 缺失信号",
    "6. 当前Antardasha → 时间事件",
    "不够5条就输出3-4条，不要凑数。",
    "",
    "## 第三步：调用 evaluate_validation 统计结果",
    "## 第四步：命中率高则调用 generate_vedic_report",
  ].join("\n"),
  tool_ids: ["collect_birth_data", "generate_validation_statements", "evaluate_validation", "generate_vedic_report"],
  workflow: null,
};
